### ISSUE TITLE
Family Weights Calculator.py error

### ISSUE THREAD

**Issue by weiweihuanghuang** [jpt/font-scripts#2]
I tried to run this in Glyphs Version 2.6.5 (1340) and got this error
```
Start
Traceback (most recent call last):
  File "Family Weights Calculator.py", line 180, in <module>
    FamilySteps()
  File "Family Weights Calculator.py", line 36, in __init__
    self.w.maxStem = vanilla.EditText( (inset+110, linePos, 32, 20), int(self.minMax()[1]), sizeStyle = 'small')
TypeError: 'NoneType' object has no attribute '__getitem__'
End
```

**Comment by jpt** [comment]
hmm weird, I just updated to 1340 and can't reproduce that error, I'll look into it
